# Generated by Django 3.1 on 2020-08-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_date_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='absolute',
            field=models.FloatField(default=0),
        ),
    ]
